=== Atgue2527/LMSGI_DTD/AV01.1 DTD + XML/c - joc 2/joc2.dtd
<!ELEMENT joc (titol, companyia, plataforma, anyLlançament, personatges, nivells)>
    <!ELEMENT titol (#PCDATA)>
    <!ELEMENT companyia (#PCDATA)>
    <!ELEMENT plataforma (#PCDATA)>
    <!ELEMENT anyLlançament (#PCDATA)>
    <!ELEMENT personatges (personatge+)>
        <!ELEMENT personatge (nomp)>
            <!ELEMENT nomp (#PCDATA)>
            <!ATTLIST personatge tipus CDATA #REQUIRED>
    <!ELEMENT nivells (nivell+)>
        <!ELEMENT nivell (nomn)>
            <!ELEMENT nomn (#PCDATA)>
            <!ATTLIST nivell dificultat (baixa | mitjana | alta) #REQUIRED>

=== Atgue2527/LMSGI_DTD/AV01.1 DTD + XML/c - joc 2/joc2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE joc SYSTEM "joc2.dtd">

<joc>
    <titol>Jak and Daxter: The Precursor Legacy</titol>
    <companyia>Naughty Dog</companyia>
    <plataforma>PlayStation</plataforma>
    <anyLlançament>2001</anyLlançament>
    <personatges>
        <personatge tipus='heroi'>
            <nomp>Jak</nomp>
        </personatge>
        <personatge tipus='company'>
            <nomp>Daxter</nomp>
        </personatge>
        <personatge tipus='mentora'>
            <nomp>Samos</nomp>
        </personatge>
    </personatges>
    <nivells>
        <nivell dificultat='baixa'>
            <nomn>Geyser Rock</nomn>
        </nivell>
        <nivell dificultat='mitjana'>
            <nomn>Sandover Village</nomn>
        </nivell>
        <nivell dificultat='alta'>
            <nomn>Gol and Maia's Citadel</nomn>
        </nivell>
    </nivells>
</joc>
