=== Atgue2527/LMSGI_DTD/AV01.1 DTD + XML/d - joc 3/joc3.dtd
<!ELEMENT joc (titol, companyia, plataforma, anyLlançament, modesJoc, personatges, regions)>
    <!ELEMENT titol (#PCDATA)>
    <!ELEMENT companyia (#PCDATA)>
    <!ELEMENT plataforma (#PCDATA)>
    <!ELEMENT anyLlançament (#PCDATA)>
    <!ELEMENT modesJoc (mode+)>
        <!ELEMENT mode (#PCDATA)>
            <!ATTLIST mode principal (si | no) #REQUIRED>
    <!ELEMENT personatges (personatge+)>
        <!ELEMENT personatge (nomp)>
            <!ELEMENT nomp (#PCDATA)>
            <!ATTLIST personatge tipus CDATA #REQUIRED>
            <!ATTLIST personatge jugable (si | no) #REQUIRED>
    <!ELEMENT regions (regio+)>
        <!ELEMENT regio (nomr, nota?)>
            <!ELEMENT nomr (#PCDATA)>
            <!ELEMENT nota (#PCDATA)>
            <!ATTLIST regio clima CDATA #REQUIRED>

=== Atgue2527/LMSGI_DTD/AV01.1 DTD + XML/d - joc 3/joc3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE joc SYSTEM "joc3.dtd">

<joc>
    <titol>The Legend of Zelda: Breath of the Wild</titol>
    <companyia>Nintendo</companyia>
    <plataforma>Nintendo Switch</plataforma>
    <anyLlançament>2017</anyLlançament>
    <modesJoc>
        <mode principal="si">Món obert</mode>
        <mode principal="no">Santuari</mode>
        <mode principal="no">Combat contra caps</mode>
    </modesJoc>
    <personatges>
        <personatge tipus="heroi" jugable="si">
            <nomp>Link</nomp>
        </personatge>
        <personatge tipus="princesa" jugable="no">
            <nomp>Zelda</nomp>
        </personatge>
        <personatge tipus="antagonista" jugable="no">
            <nomp>Ganon</nomp>
        </personatge>
    </personatges>
    <regions>
        <regio clima="fred">
            <nomr>Hebra</nomr>
        </regio>
        <regio clima="càlid">
            <nomr>Gerudo</nomr>
        </regio>
        <regio clima="neutre">
            <nomr>Centre d'Hyrule</nomr>
            <nota>Zona amb molts guardians.</nota>
        </regio>
    </regions>
</joc>
